apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node-iuvity
  labels:
    app: test-node-iuvity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-node-iuvity
  template:
    metadata:
      labels:
        app: test-node-iuvity
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - test-node-iuvity
              topologyKey: kubernetes.io/hostname
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: test-node-iuvity
        image: test-node-iuvity:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "3500"
        ports:
        - containerPort: 3500
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3500
          initialDelaySeconds: 15
          periodSeconds: 20
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL 